### ISSUE TITLE
`repo_downloader.sh` not found 

### ISSUE THREAD

**Issue by charlesfg** [AUEB-BALab/VulinOSS#1]
First attempt to run the code, the `repo_downloader.sh` referenced in the documentation does not exist.

**Comment by AntonisGkortzis** [comment]
Added in commit [ee8f7e3fc3b285598b3ec766cd70944f555fc49c](https://github.com/AUEB-BALab/VulinOSS/commit/ee8f7e3fc3b285598b3ec766cd70944f555fc49c)
